{% set version = "0.1.0" %}

package:
  name: appnope
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/appnope/appnope-{{ version }}.tar.gz
  sha256: 8b995ffe925347a2138d7ac0fe77155e4311a0ea6d6da4f5128fe4b3cbe5ed71

build:
  number: 1002
  skip: true  # [not osx]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - appnope

about:
  home: http://github.com/minrk/appnope
  license: BSD 2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Disable App Nap on OS X 10.9
  dev_url: http://github.com/minrk/appnope
  doc_url: https://github.com/minrk/appnope

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - ocefpaf
