{% set version = "0.1.4" %}

package:
  name: appnope
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/appnope/appnope-{{ version }}.tar.gz
  sha256: 1de3860566df9caf38f01f86f65e0e13e379af54f9e4bee1e66b48f2efffd1ee

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >=2.7
    - pip
  run:
    - python >=2.7

test:
  imports:
    - appnope

about:
  home: http://github.com/minrk/appnope
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Disable App Nap on macOS >=10.9"
  dev_url: http://github.com/minrk/appnope
  doc_url: https://github.com/minrk/appnope

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - ocefpaf
