appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ed5O1kMkXPM4QwAPrD3tc4JFviySrGz43hNCuShb9URGnAMKGWRSFwuJ3cAMp5e9/zz+ac0nWu7nVHxyB2VzGmQzClq4H1JL8xci/sejGAu80AVnXGnaGIJ/gOF6Vo9CDOaVxjHE4wxzAaUMG1DQ/3gSsTjmrh90Ikvh9cDsTVquUZUF9Welsb8mmmZup4NyJw9E3VM74vBCdL5EGf2osBFPq8w0K6BOb2+iLgU9eSLFWDJ8wA4T1gpGODKSsXwEI25YJBVKgO+0IGokucYRY4UHzTauoa6mLAZjPJ0y8a2NaFD6yiaIq2Nbu3bbHoncnpZDFjzviWLqHJ+nTarNvdySIGpsYsDuxyg0FWWHMPIOnkDh/M3O+aD9TjwnkcdLhXHTKpT5TbOnyZESpX9qR3YbLWMDAOsiE9O22Q1zK3gN5Ge8AAZnue8Kq2bgVw0iVcSctvrBVv1xMFul4HhjRovctvJXk6PHOSyFsW3VoPMeYQyOxUd9DGDqCwXCg8WcZwPJ7R0bk93o9uDddyii2P1b7En6/RyIx03bmkf8c/7Jq9vwOBvJTCmP0oNEi3/NrTFFRmXTvta7SZP+dZbvUWDoKrdNIkdEIz+sFBGqtkrPdv2HgT8RlKwufar9ySveoMHgv05KNIGx/Yxs/oSTxnxYzuAA8I9rOeLFj0BWcZs=}
